export enum BlogCategory {
    ComputerVision = "Computer Vision",
    WebDevelopment = "Web Development",
    DataScience = "Data Science",
    NLP = "NLP",
    Infrastructure = "Infrastructure",
    ReinforcementLearning = "Reinforcement Learning",
    GraphNeuralNetworks = "Graph Neural Networks",
    Mathematics = "Mathematics",
    Frontend = "Frontend",
    Backend = "Backend",
    DeepLearning = "Deep Learning",
    PracticalMachineLearning = "Practical Machine Learning",
    TheoreticalMachineLearning = "Theoretical Machine Learning",
    Engineering = "Engineering",
    LowLevel = "Low Level",
}

export enum TechStack {
    Python = "Python",
    PyTorch = "PyTorch",
    TensorFlow = "TensorFlow",
    Keras = "Keras",
    FastAPI = "FastAPI",
    Docker = "Docker",
    Azure = "Azure",
    GoogleCloud = "Google Cloud",
    TypeScript = "TypeScript",
    JavaScript = "JavaScript",
    Golang = "Golang",
    React = "React",
    Java = "Java",
    CPP = "C++",
}